### ISSUE TITLE
[fud] Use of `traceback.print_exc(e)` in `extract.py` fails

### ISSUE THREAD

**Issue by mortbopet** [cucapra/calyx#690]
When the following exception handler is executed:
https://github.com/cucapra/calyx/blob/cb9821a53c658cf9beb7a31bfbf4ff3022366770/fud/fud/stages/vivado/extract.py#L105-L109

with a `FileNotFoundError` (for instance, if `main_utilization_placed.rpt` is not found within the source directory), an additional exception is raised from the `traceback.print_exc(e)` call:
```
Traceback (most recent call last):
  File "/home/morten/.local/lib/python3.8/site-packages/fud/stages/vivado/extract.py", line 55, in futil_extract
    impl_parser = rpt.RPTParser(
  File "/home/morten/.local/lib/python3.8/site-packages/fud/stages/vivado/rpt.py", line 13, in __init__
    with open(filepath, "r") as data:
FileNotFoundError: [Errno 2] No such file or directory: 'outdir/out/FutilBuild.runs/impl_1/main_utilization_placed.rpt'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/morten/.local/bin/fud", line 8, in <module>
    sys.exit(main())
  File "/home/morten/.local/lib/python3.8/site-packages/fud/main.py", line 306, in main
    exec.run_fud(args, cfg)
  File "/home/morten/.local/lib/python3.8/site-packages/fud/exec.py", line 108, in run_fud
    result = ed.stage.run(data, sp)
  File "/home/morten/.local/lib/python3.8/site-packages/fud/stages/__init__.py", line 212, in run
    step()
  File "/home/morten/.local/lib/python3.8/site-packages/fud/stages/__init__.py", line 242, in __call__
    self.output.data = self.func(*self.args)
  File "/home/morten/.local/lib/python3.8/site-packages/fud/stages/vivado/stage.py", line 166, in extract
    return futil_extract(Path(directory.name))
  File "/home/morten/.local/lib/python3.8/site-packages/fud/stages/vivado/extract.py", line 108, in futil_extract
    traceback.print_exc(e)
  File "/usr/lib/python3.8/traceback.py", line 163, in print_exc
    print_exception(*sys.exc_info(), limit=limit, file=file, chain=chain)
  File "/usr/lib/python3.8/traceback.py", line 103, in print_exception
    for line in TracebackException(
  File "/usr/lib/python3.8/traceback.py", line 508, in __init__
    self.stack = StackSummary.extract(
  File "/usr/lib/python3.8/traceback.py", line 340, in extract
    if limit >= 0:
TypeError: '>=' not supported between instances of 'FileNotFoundError' and 'int'
```

On my machine this can be reproduced by:
> fud exec --from synth-files --to resource-estimate ${any directory}

**Comment by sampsyo** [comment]
Oops! At least the fix is easy: this should just be `traceback.print_exc()` with no arguments (cf [the docs](https://docs.python.org/3/library/traceback.html#traceback.print_exc)). The `as e` in the `except:` line can also therefore be removed.
